# Generated by Django 2.1.7 on 2019-02-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='photo',
        ),
        migrations.AddField(
            model_name='file',
            name='file_data',
            field=models.FileField(blank=True, null=True, upload_to='clientes_foto'),
        ),
    ]
